## Data Analyst
- Insights - Charts
- SQL
- Power Bi - Charts
- One shot Query


## Data Scientists
- Excel
- Python - nupy, pandas
- Scale - Millions of rows
- Scikit - data prediction
- Matplot, seabord - Charts - (Rapid prototyping)
- Line by line (step)

In [3]:
import numpy as np

In [5]:
marks1 = [90, 80, 20, 40]
print(marks1 * 2)

[90, 80, 20, 40, 90, 80, 20, 40]


In [6]:
mark2 = np.array([90, 80, 20, 40])
print(mark2 * 2)

[180 160  40  80]


## Python way to double the list

In [7]:
marks_dbl = [mark * 2 for mark in marks1]
marks_dbl

[180, 160, 40, 80]

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
fives = np.ones(20) * 5
fives


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

In [22]:
np.arange(1,11) < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [27]:
np.array([1, 11]) - np.array([1, 11])


array([0, 0])

# Task 1.1
# 1-200 only even numbers | With skip of arange


In [24]:
np.arange(0, 201, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

# Task 1.2
# 1-200 only even numbers | Dont use skip of arange

In [ ]:
np.arange(0, 201, 2)
