## Data Analyst
- Insights - Charts
- SQL
- Power Bi - Charts
- One shot Query


## Data Scientists
- Excel
- Python - nupy, pandas
- Scale - Millions of rows
- Scikit - data prediction
- Matplot, seabord - Charts - (Rapid prototyping)
- Line by line (step)

In [8]:
import numpy as np

In [ ]:
marks1 = [90, 80, 20, 40]
print(marks1 * 2)

In [ ]:
mark2 = np.array([90, 80, 20, 40])
print(mark2 * 2)

## Python way to double the list

In [ ]:
marks_dbl = [mark * 2 for mark in marks1]
marks_dbl

In [ ]:
np.ones(10)

In [ ]:
fives = np.ones(20) * 5
fives


In [ ]:
np.arange(1,11) < 5

In [ ]:
np.array([1, 11]) - np.array([1, 11])


# Task 1.1
# 1-200 only even numbers | With skip of arange


In [ ]:
np.arange(0, 201, 2)

# Task 1.2
# 1-200 only even numbers | Dont use skip of arange

In [ ]:
np.arange(0, 201, 2)


## Statistical oriented - mean, mode, median, std
- mean -> average
- mode -> the most repeated number (most popular)
- median -> middle number when in ascending order

In [9]:
marks = np.random.randint(40, 100, 10)
print(marks)
print(marks.mean())


[96 42 78 98 78 67 63 91 40 63]
71.6


In [ ]:
import numpy as np

##### Task 1
## At the every year tell me balance for 10 years
## Clue: General formula
## 1102.5 -> 1000 +
## [1050, 1102.5 ...., ]

Investment = 1_000
interest_rate = 1.05
n = 1
num_years =np.arange(1,11)

balance_over_years = Investment * interest_rate ** num_years
balance_over_years


np.float64(1628.894626777442)

In [18]:
# Task 2: Balance at the end of year 10
balance_over_years[9]

np.float64(1628.894626777442)

In [19]:
# Task 3: Percentage increase compared to the first year

current_balance = balance_over_years[-1]
profit = (current_balance - Investment) / Investment
print(profit * 100)

62.8894626777442


In [26]:
nums = np.random.randint(1, 4, 10)
nums

array([2, 2, 3, 3, 2, 1, 2, 1, 2, 2], dtype=int32)

In [27]:
unique_nums = np.unique(nums)
unique_nums

array([1, 2, 3], dtype=int32)

## Task 1
 
hourly_visitors = [468, 279,  73, 272 ,406 ,128 ,302 ,216, 140, 82]
 
- 1.1 Total visitors in the day?
- 1.2 Which is the peak hour?
- 1.3 On average how many people visit per hour
 
### Output
```
Total visitors in the day: 2366
Peak hour: 1
Average people visit: 237
```

In [32]:
# Task 1.1

hourly_visitors = [468, 279,  73, 272 ,406 ,128 ,302 ,216, 140, 82]
total_visits = sum(hourly_visitors)
print(f" Total visitors in the day: {total_visits}")

 Total visitors in the day: 2366


In [33]:
# Task 1.2
from statistics import mode


peak_hour = mode(hourly_visitors)
print (f"Peak hour: {np.argmax(hourly_visitors) + 1}")

Peak hour: 1


In [34]:
# Task 1.3
print(f"Average people visit: {round(np.mean(hourly_visitors))}")

Average people visit: 237


In [36]:
words = np.array(["hello", "world", "numpy"])
np. char.upper(words)
np. char.capitalize(words)

array(['Hello', 'World', 'Numpy'], dtype='<U5')

## Task 2
Normalize the Array:
 
- 2.1 Trim leading and trailing spaces.
- 2.2 Convert all items to lowercase.
- 2.3 Ensure there are no duplicate items in the array.
 

In [43]:
import numpy as np

# Given array
items = np.array([' Apple', 'banana ', 'GRAPE', 'cucumber', 'Pineapple', ' tomato ', 'Orange', ' lemon', 'Kiwi ', 'mango', 'blueberry ', ' raspberry'])
normalized_items = np.unique([item.strip().lower() for item in items])
normalized_items

array(['apple', 'banana', 'blueberry', 'cucumber', 'grape', 'kiwi',
       'lemon', 'mango', 'orange', 'pineapple', 'raspberry', 'tomato'],
      dtype='<U9')

## Task 3 (Challenging)
Filtering Operations:
- 3.1 Find and display all items that start with the letter 'b'.
- 3.2 Find and display all items that contain the letter 'e' exactly once.

In [47]:
items = np.array([' Apple', 'banana ', 'GRAPE', 'cucumber', 'Pineapple', ' tomato ', 'Orange', ' lemon', 'Kiwi ', 'mango', 'blueberry ', ' raspberry'])
starts_b = items[np.char.startswith(items, 'b')]
print(f"Words that starts with b:", starts_b)

Words that starts with b: ['banana ' 'blueberry ']


In [51]:
display_e = items[np.char.count(items, 'e') == 1]
print(f"Words that contatins 'e' once:", display_e)

Words that contatins 'e' once: [' Apple' 'cucumber' 'Orange' ' lemon' ' raspberry']


## 2D Matrix / Arrays


In [52]:
num_3x3 = np.array([[1, 3, 4],
                    [6, 10, 77],
                    [9, 20, 24]
])

In [55]:
num_3x3


array([[ 1,  3,  4],
       [ 6, 10, 77],
       [ 9, 20, 24]])

In [56]:
num_3x3 * 2

array([[  2,   6,   8],
       [ 12,  20, 154],
       [ 18,  40,  48]])